name: predictive_ltv_survival_pipeline
version: 0.1.0
config-version: 2

profile: predictive_ltv_survival_pipeline

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: [">=1.7.0", "<2.0.0"]

models:
  predictive_ltv_survival_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
